#!/bin/sh

unset Cabac
unset qpoffset
unset deblock_filter_control
unset disable_deblocking_filter_idc
unset slice_alpha_c0_offset_div2
unset slice_beta_offset_div2
unset nRows
unset nDmv_X
unset nDmv_Y
unset bInter8x8PredEn
unset bInter8x16PredEn
unset bInter16x8PredEn
unset bInter16x16PredEn
unset bIntra16x16PredEn
unset constrained_intra_pred_flag
unset u32Intra16x16Penalty
unset u32Intra4x4Penalty
unset bIntraPlanarPenalty
unset VENC_RC
unset RcType
unset Bitrate
unset AbrMaxBitrate
unset VbrMinQp
unset VbrMaxQp
unset VENC_GOP
unset Qfactor
unset VENC_ROI0_EN
unset VENC_ROI0_X
unset VENC_ROI0_Y
unset VENC_ROI0_W
unset VENC_ROI0_H
unset VENC_ROI0_Qp
unset VENC_ROI1_EN
unset VENC_ROI1_X
unset VENC_ROI1_Y
unset VENC_ROI1_W
unset VENC_ROI1_H
unset VENC_ROI1_Qp
unset VENC_ROI_SRC_RATE
unset VENC_ROI_DST_RATE
unset VENC_Crop
unset VENC_Crop_X
unset VENC_Crop_Y
unset VENC_Crop_W
unset VENC_Crop_H
unset Idr
unset EnableIdr
unset EnableIdrFrame
unset VENC_ChangeHeight
unset VENC_ChangeQp
unset VENC_ChangeGop
unset VENC_ChangeToFpsN
unset VENC_ChangeToFpsM
unset VENC_ChangeBitrate