all:
	$(MAKE) -f ./MakeObj.mk all
	$(MAKE) -f ./MakeLib.mk all
	$(MAKE) -f ./MakeApp.mk all
	$(MAKE) -f ./MakeObjX86.mk all
	$(MAKE) -f ./MakeLibX86.mk all
	$(MAKE) -f ./MakeAppX86.mk all
	
clean:
	$(MAKE) -f ./MakeApp.mk clean
	$(MAKE) -f ./MakeLib.mk clean
	$(MAKE) -f ./MakeObj.mk clean
	$(MAKE) -f ./MakeAppX86.mk clean
	$(MAKE) -f ./MakeLibX86.mk clean
	$(MAKE) -f ./MakeObjX86.mk clean