CODEDEFINE += -D$(DB_PROJECT)
CODEDEFINE += -DTRANS_BUFFER=$(DB_TRANS_BUFFER_SIZE)
CODEDEFINE += -DSOCKET_ADDR=\"\/tmp\/mdb_socket\"
ifeq ($(DB_USE_SOCKET), 1)
    CODEDEFINE += -DUSE_SOCKET
endif
ifeq ($(DB_USE_SHM), 1)
    CODEDEFINE += -DUSE_SHM
endif
