.PHONY : all clean
all:
	$(MAKE) -f ./mdbcmd.mk all
	$(MAKE) -f ./mdbrec.mk all
	$(MAKE) -f ./mdbcmdX86.mk all
	$(MAKE) -f ./mdbrecX86.mk all

clean:
	$(MAKE) -f ./mdbcmd.mk clean
	$(MAKE) -f ./mdbrec.mk clean
	$(MAKE) -f ./mdbcmdX86.mk clean
	$(MAKE) -f ./mdbrecX86.mk clean
